using System;
using System.Collections.Generic;
using System.Text;

namespace lectorArchivo.Transversal
{
    public enum Categoria
    {
        IDENTIFICADOR, NUMERO_ENTERO, NUMERO_DECIMAL, SUMA, RESTA, MULTIPLICACION, DIVISION, MODULO, ASIGNACION, MAYOR_QUE, MENOR_QUE, IGUAL_QUE, MAYOR_O_IGUAL_QUE, MENOR_O_IGUAL_QUE, DIFERENTE_QUE, PARENTESIS_ABRE, PARENTESIS_CIERRA, FIN_DE_ARCHIVO, PALABRA_RESERVADA_A, PALABRA_RESERVADA_B, PALABRA_RESERVADA_C

    }
}
